### ISSUE TITLE
.mp3 isn't a supported audio format

### ISSUE THREAD

**Issue by aidswidjaja** [dippyshere/Newest-Super-Human-Bros-PC#16]
Now that everything is working fine... another pygame error. This one looks relatively straightforward though.
## System version
```
Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F132)
      Kernel Version: Darwin 18.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Adrian's MacBook Pro
      User Name: Adrian Widjaja (Adrian)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 30 days 22:42
```
## `which python3`
```
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
```
## `pip3 list`
```
Package     Version
----------- ----------
altgraph    0.16.1
Django      2.2.3
macholib    1.11
modulegraph 0.17
pip         19.3
py2app      0.19
pygame      2.0.0.dev4
pytz        2019.1
setuptools  40.8.0
sqlparse    0.3.0
wheel       0.33.4
```
## Terminal output
```
adrian:~ Adrian$ cd /Users/Adrian/Newest-Super-Human-Bros-PC-0.8.1-beta\ 2
adrian:Newest-Super-Human-Bros-PC-0.8.1-beta 2 Adrian$ python3 /Users/Adrian/Newest-Super-Human-Bros-PC-0.8.1-beta\ 2/Newest\ Super\ Human\ Bros\ PC.py
pygame 2.0.0.dev4 (SDL 2.0.10, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
['69', '420', '69420', '00:00:00']
18528
18528
name()
Global cache: 18528
game_intro()
Global cache: 18528
False
Traceback (most recent call last):
  File "/Users/Adrian/Newest-Super-Human-Bros-PC-0.8.1-beta 2/Newest Super Human Bros PC.py", line 2907, in <module>
    name()
  File "/Users/Adrian/Newest-Super-Human-Bros-PC-0.8.1-beta 2/Newest Super Human Bros PC.py", line 668, in name
    game_intro()
  File "/Users/Adrian/Newest-Super-Human-Bros-PC-0.8.1-beta 2/Newest Super Human Bros PC.py", line 686, in game_intro
    music = pygame.mixer.music.load('audio/sm64fs.mp3')
pygame.error: Unrecognized audio format
```
As far as I'm concerned, wav, ogg are the only supported by pygame. http://www.pygame.org/docs/ref/mixer.html

**Comment by dippyshere** [comment]
hmm ive had problems with wav but mp3 was working fine. ill try oggs

**Comment by dippyshere** [comment]
ok making the sounds ogg has no effect on my end so it should hopefully fix it for you
ill test if it fixes issue #14

**Comment by dippyshere** [comment]
it doesnt seem to fix issue #14 ffs

**Comment by aidswidjaja** [comment]
lol, assembling from source now, will let you know the outcome

**Comment by dippyshere** [comment]
i havnt commited it yet

**Comment by aidswidjaja** [comment]
Oh okay, well I got a new error anyways

```
adrian:Newest-Super-Human-Bros-PC Adrian$ python3 /Users/Adrian/Newest-Super-Human-Bros-PC/Newest\ Super\ Human\ Bros\ PC.py
pygame 2.0.0.dev4 (SDL 2.0.10, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
['69', '420', '69420', '00:00:00']
18528
Traceback (most recent call last):
  File "/Users/Adrian/Newest-Super-Human-Bros-PC/Newest Super Human Bros PC.py", line 2858, in <module>
    fade_out(1280,720)
  File "/Users/Adrian/Newest-Super-Human-Bros-PC/Newest Super Human Bros PC.py", line 601, in fade_out
    pygame.display.flip()
pygame.error: Window surface is invalid, please call SDL_GetWindowSurface() to get a new surface
```

At this point this is probably an issue with incompatibility with pygame 2.0.0.  You might want to look into virtualenv or get your teacher to run it off your laptop as 1.9.6 will break pygame but 2.0.0 might break your code. 

Idk at this point, you might need to look at getting it run off 1.9.6 with your teacher and hope it works alright. If 1.9.6 works with @jean1398reborn, then do not pygame==2.0.0dev4. However, I'm not sure what you want to do.

Ftr, everything works on ubuntu.

**Comment by dippyshere** [comment]
lol. yeah. my teacher said that she will run it on (her) pc. she is aware that pygame is unpredictable on mac

**Comment by dippyshere** [comment]
i think ill just close the issue for now. ive finally pushed the commit that took ages to fetch origin. anyway hope that works by random chance.

**Comment by aidswidjaja** [comment]
#UbuntuFTW

**Comment by dippyshere** [comment]
lol yes. you can go to 125% volume. best feature of an os

**Comment by dippyshere** [comment]
if you're coming here from google, try the **latest** version of pygame (i dont remember if pygame 2 is released or not yet)

**Comment by Magpiny** [comment]
Pygame 2 does not recognise mp3 files. I get this "unrecognised audio format" every time. Am using pygame version 2.0.1

**Comment by dippyshere** [comment]
what os are you running? for compatibility, it's better to use OGG files for audio in pygame. mp3 support is flakey and unsupported on debian linux. you can use audition or audacity to convert your files between formats

for the best format, I recommend a 16 bit 44100hz ogg, but pygame 2 adds support for 32 bit audio.

**Comment by Magpiny** [comment]
Am using Manjaro Linux. Is there a workaround for this?

**Comment by Magpiny** [comment]
Also I noticed that there are many versions of .ogg in pygame and am kinda
confused on which one to use. Could you please suggest the right/best ogg
format to use?

**Comment by dippyshere** [comment]
for this project, I used a 32 bit 48,000hz ogg. you shouldn't have to worry about the specific codec, but if you need to choose, go opus.

the key is having all your audio files in the same bit depth and sample rate, as if you don't, the mismatched files will play at the wrong pitch/speed.

**Comment by Magpiny** [comment]
Thanks for the tip!
