### ISSUE TITLE
Crashing Error/ Not Responding

### ISSUE THREAD

**Issue by stellaurora** [dippyshere/Newest-Super-Human-Bros-PC#7]
Upon loading and initing the game the window displays a blank pygame window canvas. after a short moment of waiting it switches to where the 'loading..' screen should be but remains black and continues unresponding until the main menu appears with no animation playing. The cutscene function animations also do not play correctly and meerly cause the window to hang.

Specs:

Mac Os Mojave
-
Intel i5 5520u
Intel HD 6000 Graphics
8 GB DDR3 Memory 
-

It seems that the window 'hangs' even though its attempting to blit and update the screen none of it actually updates. 

potential maybe by using display.flip instead of update?

**Comment by dippyshere** [comment]
Hey there, u/jean1398reborn! I want to let you know I am currently aware of the issue and will be releasing an update to address it in 2 years. In the mean time I will be starting sub-wide downtime as of now.

Stay awesome community!
-magic ghost
/s

**Comment by dippyshere** [comment]
Thanks for bringing this to my attention jean

**Comment by dippyshere** [comment]
when calling update without any parameters it will function identically to flip so flip doesn't do anything. i've tried flip anyway and we found no luck

**Comment by stellaurora** [comment]
Bug fixed with latest release.
